version: '3.9'
services:
  php:
    build: ./provision/shared
    volumes:
      - .:/var/www/html
    network_mode: host

  db:
    image: percona:5.7-centos
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: database
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
    network_mode: host

volumes:
  db:
